[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ledtrack"
version = "0.1.10"
description = "Learning-Estimation-Decision Cell Tracking"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "tqdm==4.67.3",
    "hydra-core==1.3.2",
    "omegaconf==2.3.0",
    "tifffile",
    "scipy==1.15.3",
    "pandas==2.3.3",
    "scikit-image==0.25.2",
    "opencv-python",
    "ortools==9.15.6755",
    "imagecodecs==2025.3.30",
    "ete3==3.1.3",
    "scikit-learn==1.7.2",
    "PyQt5==5.15.11",
]

[project.scripts]
ledtrack = "ledtrack.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ledtrack = ["config/*", "data/**/*", "*.png", "*.gif"]